version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: "3.11.9"
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - app_network
    depends_on: []  # Removed db dependency

networks:
  app_network:


  # db:
  #   image: postgres:13
  #   container_name: postgres_db
  #   ports:
  #     - "5432:5432"
  #   env_file:
  #     - .env
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #     - ./init_schemas.sql:/docker-entrypoint-initdb.d/init_schemas.sql
  #   networks:
  #     - app_network
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5







